/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as StakeholderCrmRouteImport } from './routes/stakeholder-crm'
import { Route as SettingsTeamRouteImport } from './routes/settings-team'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RecommendationLettersRouteImport } from './routes/recommendation-letters'
import { Route as PostAnalyticsRouteImport } from './routes/post-analytics'
import { Route as PositioningRouteImport } from './routes/positioning'
import { Route as ParliamentTrackerRouteImport } from './routes/parliament-tracker'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as MediaWatchRouteImport } from './routes/media-watch'
import { Route as IssueRadarRouteImport } from './routes/issue-radar'
import { Route as GrievancesRouteImport } from './routes/grievances'
import { Route as FundsProjectsRouteImport } from './routes/funds-projects'
import { Route as DailyBriefingRouteImport } from './routes/daily-briefing'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BriefingsSpeechesRouteImport } from './routes/briefings-speeches'
import { Route as IndexRouteImport } from './routes/index'

const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholderCrmRoute = StakeholderCrmRouteImport.update({
  id: '/stakeholder-crm',
  path: '/stakeholder-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings-team',
  path: '/settings-team',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationLettersRoute = RecommendationLettersRouteImport.update({
  id: '/recommendation-letters',
  path: '/recommendation-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const PostAnalyticsRoute = PostAnalyticsRouteImport.update({
  id: '/post-analytics',
  path: '/post-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PositioningRoute = PositioningRouteImport.update({
  id: '/positioning',
  path: '/positioning',
  getParentRoute: () => rootRouteImport,
} as any)
const ParliamentTrackerRoute = ParliamentTrackerRouteImport.update({
  id: '/parliament-tracker',
  path: '/parliament-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaWatchRoute = MediaWatchRouteImport.update({
  id: '/media-watch',
  path: '/media-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueRadarRoute = IssueRadarRouteImport.update({
  id: '/issue-radar',
  path: '/issue-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievancesRoute = GrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsProjectsRoute = FundsProjectsRouteImport.update({
  id: '/funds-projects',
  path: '/funds-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyBriefingRoute = DailyBriefingRouteImport.update({
  id: '/daily-briefing',
  path: '/daily-briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsSpeechesRoute = BriefingsSpeechesRouteImport.update({
  id: '/briefings-speeches',
  path: '/briefings-speeches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefings-speeches': typeof BriefingsSpeechesRoute
  '/calendar': typeof CalendarRoute
  '/daily-briefing': typeof DailyBriefingRoute
  '/funds-projects': typeof FundsProjectsRoute
  '/grievances': typeof GrievancesRoute
  '/issue-radar': typeof IssueRadarRoute
  '/media-watch': typeof MediaWatchRoute
  '/opportunities': typeof OpportunitiesRoute
  '/parliament-tracker': typeof ParliamentTrackerRoute
  '/positioning': typeof PositioningRoute
  '/post-analytics': typeof PostAnalyticsRoute
  '/recommendation-letters': typeof RecommendationLettersRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/settings-team': typeof SettingsTeamRoute
  '/stakeholder-crm': typeof StakeholderCrmRoute
  '/visitors': typeof VisitorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefings-speeches': typeof BriefingsSpeechesRoute
  '/calendar': typeof CalendarRoute
  '/daily-briefing': typeof DailyBriefingRoute
  '/funds-projects': typeof FundsProjectsRoute
  '/grievances': typeof GrievancesRoute
  '/issue-radar': typeof IssueRadarRoute
  '/media-watch': typeof MediaWatchRoute
  '/opportunities': typeof OpportunitiesRoute
  '/parliament-tracker': typeof ParliamentTrackerRoute
  '/positioning': typeof PositioningRoute
  '/post-analytics': typeof PostAnalyticsRoute
  '/recommendation-letters': typeof RecommendationLettersRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/settings-team': typeof SettingsTeamRoute
  '/stakeholder-crm': typeof StakeholderCrmRoute
  '/visitors': typeof VisitorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefings-speeches': typeof BriefingsSpeechesRoute
  '/calendar': typeof CalendarRoute
  '/daily-briefing': typeof DailyBriefingRoute
  '/funds-projects': typeof FundsProjectsRoute
  '/grievances': typeof GrievancesRoute
  '/issue-radar': typeof IssueRadarRoute
  '/media-watch': typeof MediaWatchRoute
  '/opportunities': typeof OpportunitiesRoute
  '/parliament-tracker': typeof ParliamentTrackerRoute
  '/positioning': typeof PositioningRoute
  '/post-analytics': typeof PostAnalyticsRoute
  '/recommendation-letters': typeof RecommendationLettersRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/settings-team': typeof SettingsTeamRoute
  '/stakeholder-crm': typeof StakeholderCrmRoute
  '/visitors': typeof VisitorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefings-speeches'
    | '/calendar'
    | '/daily-briefing'
    | '/funds-projects'
    | '/grievances'
    | '/issue-radar'
    | '/media-watch'
    | '/opportunities'
    | '/parliament-tracker'
    | '/positioning'
    | '/post-analytics'
    | '/recommendation-letters'
    | '/recommendations'
    | '/reports'
    | '/sentiment'
    | '/settings-team'
    | '/stakeholder-crm'
    | '/visitors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefings-speeches'
    | '/calendar'
    | '/daily-briefing'
    | '/funds-projects'
    | '/grievances'
    | '/issue-radar'
    | '/media-watch'
    | '/opportunities'
    | '/parliament-tracker'
    | '/positioning'
    | '/post-analytics'
    | '/recommendation-letters'
    | '/recommendations'
    | '/reports'
    | '/sentiment'
    | '/settings-team'
    | '/stakeholder-crm'
    | '/visitors'
  id:
    | '__root__'
    | '/'
    | '/briefings-speeches'
    | '/calendar'
    | '/daily-briefing'
    | '/funds-projects'
    | '/grievances'
    | '/issue-radar'
    | '/media-watch'
    | '/opportunities'
    | '/parliament-tracker'
    | '/positioning'
    | '/post-analytics'
    | '/recommendation-letters'
    | '/recommendations'
    | '/reports'
    | '/sentiment'
    | '/settings-team'
    | '/stakeholder-crm'
    | '/visitors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingsSpeechesRoute: typeof BriefingsSpeechesRoute
  CalendarRoute: typeof CalendarRoute
  DailyBriefingRoute: typeof DailyBriefingRoute
  FundsProjectsRoute: typeof FundsProjectsRoute
  GrievancesRoute: typeof GrievancesRoute
  IssueRadarRoute: typeof IssueRadarRoute
  MediaWatchRoute: typeof MediaWatchRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ParliamentTrackerRoute: typeof ParliamentTrackerRoute
  PositioningRoute: typeof PositioningRoute
  PostAnalyticsRoute: typeof PostAnalyticsRoute
  RecommendationLettersRoute: typeof RecommendationLettersRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ReportsRoute: typeof ReportsRoute
  SentimentRoute: typeof SentimentRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  StakeholderCrmRoute: typeof StakeholderCrmRoute
  VisitorsRoute: typeof VisitorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholder-crm': {
      id: '/stakeholder-crm'
      path: '/stakeholder-crm'
      fullPath: '/stakeholder-crm'
      preLoaderRoute: typeof StakeholderCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-team': {
      id: '/settings-team'
      path: '/settings-team'
      fullPath: '/settings-team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation-letters': {
      id: '/recommendation-letters'
      path: '/recommendation-letters'
      fullPath: '/recommendation-letters'
      preLoaderRoute: typeof RecommendationLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-analytics': {
      id: '/post-analytics'
      path: '/post-analytics'
      fullPath: '/post-analytics'
      preLoaderRoute: typeof PostAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positioning': {
      id: '/positioning'
      path: '/positioning'
      fullPath: '/positioning'
      preLoaderRoute: typeof PositioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parliament-tracker': {
      id: '/parliament-tracker'
      path: '/parliament-tracker'
      fullPath: '/parliament-tracker'
      preLoaderRoute: typeof ParliamentTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-watch': {
      id: '/media-watch'
      path: '/media-watch'
      fullPath: '/media-watch'
      preLoaderRoute: typeof MediaWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue-radar': {
      id: '/issue-radar'
      path: '/issue-radar'
      fullPath: '/issue-radar'
      preLoaderRoute: typeof IssueRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievances': {
      id: '/grievances'
      path: '/grievances'
      fullPath: '/grievances'
      preLoaderRoute: typeof GrievancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds-projects': {
      id: '/funds-projects'
      path: '/funds-projects'
      fullPath: '/funds-projects'
      preLoaderRoute: typeof FundsProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-briefing': {
      id: '/daily-briefing'
      path: '/daily-briefing'
      fullPath: '/daily-briefing'
      preLoaderRoute: typeof DailyBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings-speeches': {
      id: '/briefings-speeches'
      path: '/briefings-speeches'
      fullPath: '/briefings-speeches'
      preLoaderRoute: typeof BriefingsSpeechesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingsSpeechesRoute: BriefingsSpeechesRoute,
  CalendarRoute: CalendarRoute,
  DailyBriefingRoute: DailyBriefingRoute,
  FundsProjectsRoute: FundsProjectsRoute,
  GrievancesRoute: GrievancesRoute,
  IssueRadarRoute: IssueRadarRoute,
  MediaWatchRoute: MediaWatchRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ParliamentTrackerRoute: ParliamentTrackerRoute,
  PositioningRoute: PositioningRoute,
  PostAnalyticsRoute: PostAnalyticsRoute,
  RecommendationLettersRoute: RecommendationLettersRoute,
  RecommendationsRoute: RecommendationsRoute,
  ReportsRoute: ReportsRoute,
  SentimentRoute: SentimentRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  StakeholderCrmRoute: StakeholderCrmRoute,
  VisitorsRoute: VisitorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
